{% set name = "tjpcov" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tjpcov-{{ version }}.tar.gz
  sha256: f7750523ba443145ef225ed8e6d0fc676af478a752c8f072a76725cbd3e4d364


build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools_scm[toml] >=6.2
  run: 
    - python >={{ python_min }}
    - scipy <1.12
    - numpy
    - jinja2
    - pyyaml
    - pyccl >=3.2
    - sacc >=0.12
    - camb
    - healpy
    - h5py
    - mpi4py
    - namaster >2

test:
  requires:
    - python {{ python_min }}
  imports:
    - tjpcov

about:
  home: https://github.com/LSSTDESC/TJPCov
  summary: Covariances for LSST DESC
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattkwiecien
    - carlosggarcia
