{% set name = "tjpcov" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tjpcov-{{ version }}.tar.gz
  sha256: fd4cd437105521e11c7f977d522cdfae75fed6d7e0c06afa599cc7eec8d7a4eb

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run: 
    - python >=3.8
    - scipy
    - numpy
    - jinja2
    - pyyaml
    - pyccl >=3.0.0
    - sacc >=0.12
    - camb
    - healpy
    - h5py
    - mpi4py
    - namaster >=1.4.0        

test:
  imports:
    - tjpcov

about:
  home: https://github.com/LSSTDESC/TJPCov
  summary: Covariances for LSST DESC
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattkwiecien
