{% set name = "tjpcov" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tjpcov-{{ version }}.tar.gz
  sha256: d269c44fd396ff90f9cb42395904231e879838462c8cf622a6b4252ca494b9b6


build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools_scm[toml] >=6.2
  run:
    - python >={{ python_min }}
    - scipy <1.12
    - numpy
    - jinja2
    - pyyaml
    - pyccl >=3.2
    - sacc >=0.12
    - camb
    - healpy
    - h5py
    - mpi4py
    - namaster >2

test:
  requires:
    - python {{ python_min }}
  imports:
    - tjpcov

about:
  home: https://github.com/LSSTDESC/TJPCov
  summary: Covariances for LSST DESC
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattkwiecien
    - carlosggarcia
    - paulrogozenski
    - RyoTerasawa
    - rreischke
